added KubeletCgroups, CgroupsPerQOS and ResolvConf to kubelet config …
k0sproject/k0s pull request #1017
Opened 2021-07-16 10:36 UTC by jasmingacic

Fixes #966 

The questionable parameter --containerd
```
Flag --containerd has been deprecated, This is a cadvisor flag that was mistakenly registered with the Kubelet. Due to legacy concerns, it will follow the standard CLI deprecation timeline before being removed.
```
According to the documentation the value passed into this argument need to be passed to 
```
--container-runtime-endpoint=unix:///run/k0s/containerd.sock
```

P.S. Cannot resolve issue with template boolean values which causes k0s to fail when bootstrapping kubelet. The template adds single qoutes around boolean value. `"cgroupsPerQOS":        "{{.CgroupsPerQOS}}",` -> `"cgroupsPerQOS":        'true',`

2021-07-19 13:23 UTC, soider requested changes
one minor thing to fix otherwise looks good

2021-07-19 13:23 UTC, soider commented on pkg/component/controller/kubeletconfig.go
> +		// "resolvConf":           "{{.Rx	esolvConf}}",
leftover

2021-07-19 13:25 UTC, jasmingacic commented on pkg/component/controller/kubeletconfig.go
> +		// "resolvConf":           "{{.Rx	esolvConf}}",
I forgot to push the changes

2021-07-28 09:52 UTC, soider approved these changes

2021-07-28 10:31 UTC, merged