Update containerd and appply go mod tidy
k0sproject/k0s pull request #1031
Opened 2021-07-27 10:41 UTC by soider

Some go.mod clean ups and updates to fix security alert

2021-07-27 10:46 UTC, trawler approved these changes

2021-07-27 10:47 UTC, jasmingacic approved these changes

2021-07-30 11:48 UTC, ncopa requested changes
I think we should use containerd 1.4.9

We should also update the containerd in the replace section.

2021-07-30 11:48 UTC, ncopa commented on go.mod
> +	github.com/containerd/containerd v1.5.4
I wonder if we should use containerd 1.4.9 instead

2021-07-30 13:23 UTC, ncopa commented on go.mod
> +	github.com/containerd/containerd v1.5.4
i think it is helm 3.6.0 that pulls in containerd 1.5.4

the help update is also breaking the windows build

2021-08-23 12:07 UTC, ncopa commented
superseded by #1055

2021-08-23 12:07 UTC, closed without merging