Remove unused command-line flags from some sub-commands
k0sproject/k0s pull request #1226
Opened 2021-10-28 10:47 UTC by kke

Signed-off-by: Kimmo Lehto <klehto@mirantis.com>

Fixes #1222 

Removes the `--config` flag from worker commands. Also tries to clean up flags in other commands (odd choices between PersistentFlags and Flags, having flags in "subcategory" no-op commands like `k0s token`)

TODO: 
- Unsure about the `etcd` "mid"-command having flags and a run-block that seemingly never executes.

2021-11-10 15:06 UTC, soider requested changes
see comment about the token config arg

2021-11-11 09:04 UTC, kke commented on cmd/token/token.go
> -	cmd.PersistentFlags().AddFlagSet(config.GetPersistentFlagSet())
This is for the "mid command", the no-op `k0s token` which just displays the list of subcommands.

2021-11-11 09:36 UTC, soider approved these changes

2021-11-11 09:37 UTC, soider commented
@trawler I think it worth merging even that #1247 has the same changes in place, just because 1247 is still draft and consists of quiet significant amount of changes

2021-11-11 10:44 UTC, kke commented
This can also be closed or merged to the #1247 

Can someone confirm that the run block in `k0s etcd` will actually never execute? I tried to have it say something but failed to invoke it in any way.

2021-11-11 10:49 UTC, soider commented on cmd/etcd/etcd.go
>  			c := CmdOpts(config.GetCmdOpts())
shouldnot, I think, `k0s etcd` is an umbrella command to group `leave` and `member-list`

2021-11-26 08:03 UTC, kke commented
Closing in favor of #1247 for now

2021-11-26 08:03 UTC, closed without merging