fix: Bug in install.md
k0sproject/k0s pull request #1291
Opened 2021-11-28 10:28 UTC by verma-kunal

Signed-off-by: Kunal Verma <vkunal321@gmail.com>

---
name: Pull Request
about: Create a Pull Request
title: ''
labels: ''
assignees: ''

---

**Issue**
Fixes #1290 

**What this PR Includes**
Fixes a small bug, that would allow to only copy the particular command from the documentation & not the generated output

2021-11-28 12:15 UTC, verma-kunal commented on docs/install.md
>      $ sudo k0s status
```suggestionsudo k0s status
```

2021-11-28 12:16 UTC, verma-kunal commented on docs/install.md
>      $ sudo k0s status
```suggestion
    sudo k0s status
```

2021-11-28 12:17 UTC, verma-kunal commented on docs/install.md
>      $ sudo k0s kubectl get nodes
```suggestion
    sudo k0s kubectl get nodes
```

2021-11-29 11:33 UTC, kke commented
Needs a rebase.

> Fixes a small bug, that would allow to only copy the particular command from the documentation & not the generated output

It is intentional to split the command and the output so that you can use the generated copy-button to copy just the command for trying it yourself without getting the output to clipboard.

2021-11-29 11:34 UTC, kke requested changes
Needs a rebase.

Also:

>Fixes a small bug, that would allow to only copy the particular command from the documentation & not the generated output

It is intentional to split the command and the output so that you can use the generated copy-button to copy just the command for trying it yourself without getting the output to clipboard.

2021-12-07 07:28 UTC, soider commented
@verma-kunal needs to be rebased over the main branch

2021-12-23 08:34 UTC, closed without merging