Default storage and extensions reworking
k0sproject/k0s pull request #1330
Opened 2021-12-09 09:22 UTC by soider

**Issue**
Fixes #1288 

**What this PR Includes**
- rework helm addons reconciler, make it more clean and easy to maintain
- migrate mentioned reconciler to the controller-runtime
- modify configuration to allow include openebs helm addon based on the boolean flag without manually modifying the helm settings

2021-12-13 10:32 UTC, mviitane requested changes
The storage documentation needs some rework:
https://docs.k0sproject.io/main/storage/

The page could start with explaining that k0s comes with preconfigured OpenEBS for local storage. It can be enabled by... and something about the storage folder configuration and what else is important.

After that we can continue with the existing content explaining:
k0s also supports any other Kubernetes storage solutions with CSI...

2021-12-13 14:48 UTC, s0j approved these changes

2021-12-15 13:31 UTC, soider commented
@mviitane added docs and test case as an example

2021-12-15 16:20 UTC, s0j approved these changes

2021-12-15 16:30 UTC, merged

2021-12-16 08:01 UTC, mviitane commented on docs/storage.md
> +The cluster wil have two storage classes available for you to use:
wil->will

2021-12-16 08:03 UTC, mviitane commented on docs/storage.md
> +bash-5.1# k0s kc get sc
The long format would be easier to understand in the example:
`k0s kubectl get storageclass`

2021-12-16 08:04 UTC, mviitane commented on docs/storage.md
> +The `openebs-hostpath` is the storage class that maps to the `
The sentence ends unexpectedly...

2021-12-16 08:08 UTC, mviitane commented on docs/storage.md
> +K0s also supports any other Kubernetes storage solutions with CSI.
This sentence should be combined with the following paragraph. Now it's too disconnected, but describing the same thing.