Autopilot code linter fix
k0sproject/k0s pull request #1733
Opened 2022-05-18 10:25 UTC by makhov

## Description

Fixes autopilot linter issues 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [ ] Auto test added

## Checklist:

- [ ] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [ ] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2022-05-25 14:31 UTC, s0j requested changes

2022-05-25 14:31 UTC, s0j commented on .github/workflows/lint.yaml
> +      - name: Run linter
I don't think changing how the CI lint works should be a part of the autopilot integration.

2022-05-25 14:49 UTC, makhov commented on go.mod
>  	k8s.io/kubernetes v1.13.0
Sorry, did it temporarily and forgot to update. Fixed now

2022-05-25 16:55 UTC, s0j approved these changes
I'm fine with this once the redunant manifest directory is removed, or if that is done in another PR.

2022-05-27 06:46 UTC, makhov commented
Thanks! I'll remove the redundant dir in a separate PR.

2022-05-27 06:46 UTC, merged