docker shim doc + kubelet flag update
k0sproject/k0s pull request #1747
Opened 2022-05-24 11:22 UTC by trawler

Signed-off-by: Karen Almog <kalmog@mirantis.com>

## Description

Fixes #1440

Documentation update on the impact of dockershim deprecation for kubernetes 1.24.
Kubelet flags are also updated to reflect the new change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-05-25 12:07 UTC, jnummelin requested changes

2022-05-25 12:07 UTC, jnummelin commented on docs/runtime.md
> +When `docker` is used as a runtime, k0s configures kubelet to create the dockershim socket at `/var/run/cri-dockerd.sock`.
This is actually not true anymore as the dockershim is NOT managed by either k0s nor kubelet

2022-05-25 12:07 UTC, jnummelin commented on docs/runtime.md
> +To run k0s with a pre-existing Docker setup, run the worker with `k0s worker --cri-socket docker:unix:///var/run/cri-dockerd.sock <token>`.
User also needs to setup the cri-dockerd shim, maybe just link to that page here?

2022-05-25 12:40 UTC, trawler commented on docs/docker-shim.md
> +sudo sed -i -e 's_^ExecStart.*_& --cri-socket docker:unix:///var/run/cri-dockerd.sock_' /etc/systemd/system/k0sworker.service
No, it's an alternative separator for the sed command, so we don't have to escape every forward slash in the socket string.

2022-05-25 14:01 UTC, jnummelin commented on docs/docker-shim.md
> +ip-10-0-62-250.eu-west-1.compute.internal   Ready    <none>          31s   v1.24.0+k0s   10.0.62.250   <none>        Ubuntu 20.04.4 LTS   5.13.0-1017-aws   containerd://1.6.4
hmm, but were "migrating" from docker to cri-dockerd+docker, right? So the _before_ state is still docker as the runtime, just via the built-in shim

2022-05-25 14:46 UTC, trawler commented on docs/docker-shim.md
> +ip-10-0-62-250.eu-west-1.compute.internal   Ready    <none>          31s   v1.24.0+k0s   10.0.62.250   <none>        Ubuntu 20.04.4 LTS   5.13.0-1017-aws   containerd://1.6.4
make sense... I'll update the doc

2022-05-31 07:58 UTC, jnummelin approved these changes

2022-05-31 08:02 UTC, merged