Add validation message for the TunneledNetworkingMode
k0sproject/k0s pull request #2153
Opened 2022-09-12 10:56 UTC by soider

Config field spec.api.tunneledNetworkingMode set to true and
    node role equals to controller+worker mode leads to running
    konnectivity-agent and kube-api on the same port.
    Due to the fact, that konnectivity-agent runs in host network, in case
    of enabled tunneledNetworkingMode, it leads to panic during the
    bootstrap.
    There is no way to validate spec.api with respect to node role,
    so it is easier to just disallow running kube-api with default port
    in case if we have tunneledNetworkingMode enabled.

Signed-off-by: Mikhail Sakhnov <msakhnov@mirantis.com>

## Description

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [ ] Auto test added

## Checklist:

- [ ] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [ ] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2022-09-14 08:21 UTC, trawler requested changes
IMO, maybe it would be a better user experience if simply add a function that checks if `a.TunneledNetworkingMode == true` and then pick an alternative kube-api port (7443, for example), if no other port was defined.
Seems to me that unless we either automate this process or highlight this limitation in the documentation - any user who tries out TunneledNetworkingMode will fail in this check.

2022-09-14 09:17 UTC, soider commented
>Seems to me that unless we either automate this process or highlight this limitation in the documentation - any user who tries out TunneledNetworkingMode will fail in this check.

That's the point to have it failed here with validation message rather than later with cryptic bind error in logs.

About the random port: I also thought that way but I am not sure, if it is a good solution. Sounds unsafe to run kube-api on random port.

2022-09-14 10:37 UTC, makhov approved these changes

2022-09-16 08:48 UTC, jnummelin commented
> Sounds unsafe to run kube-api on random port.

I agree. Also we'd need to be able to pick the same port always in case k0s or the node restarts.

2022-11-29 09:57 UTC, merged