Update docs about dockershim removal
k0sproject/k0s pull request #2928
Opened 2023-03-27 09:35 UTC by twz123

## Description

The official docs about the "metrics situation" have been merged. Update the links accordingly. Also do some slight spelling and case unifications, and add a nav link to the dockershim docs page.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-03-27 12:03 UTC, juanluisvaladas requested changes
Other than the sentence, LGTM

2023-03-27 15:30 UTC, twz123 commented on docs/troubleshooting.md
> +There's currently no easy workarounds for this.
What about

> Currently, there is no easy solution to this problem.

?

2023-03-28 07:44 UTC, juanluisvaladas commented on docs/troubleshooting.md
> +There's currently no easy workarounds for this.
I like that

2023-03-28 07:44 UTC, juanluisvaladas commented on docs/troubleshooting.md
> +There's currently no easy workarounds for this.
I like that.

2023-03-29 07:44 UTC, twz123 commented on docs/troubleshooting.md
> +There's currently no easy workarounds for this.
Done.

2023-03-29 13:52 UTC, juanluisvaladas approved these changes
LGTM

2023-03-29 16:38 UTC, merged