Feature gates as config field
k0sproject/k0s pull request #2987
Opened 2023-04-11 10:32 UTC by mikhail-sakhnov

## Description

Exposes feature-gates as cluster config field letting to enable them without overriding extraArgs or kubelet profiles

Related #2645 
#2693 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

## How Has This Been Tested?

- [X] Manual test
- [X] Auto test added

## Checklist:

- [X] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [X] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-04-13 09:39 UTC, juanluisvaladas requested changes
I added a note regarding one function, the rest looks good.

2023-04-13 09:39 UTC, juanluisvaladas commented on pkg/apis/k0s.k0sproject.io/v1beta1/feature_gates.go
> +func (fg *FeatureGate) AddFeatureGatesToArgs(args stringmap.StringMap, component string) stringmap.StringMap {
This function isn't used anywhere and doesn't do what it claims to do.
Can it be removed?

2023-04-17 12:08 UTC, makhov approved these changes

2023-04-17 12:39 UTC, juanluisvaladas approved these changes

2023-04-17 12:39 UTC, merged