print external LB address in admin kubeconfig
k0sproject/k0s pull request #669
Opened 2021-01-29 11:30 UTC by trawler

Signed-off-by: Karen Almog <kalmog@mirantis.com>

**Issue**

**What this PR Includes**
When printing Admin's kubeconfig using `kubeconfig admin`, replace the localhost address with an external Address, if exists.

2021-01-29 12:09 UTC, jnummelin submitted a review, later dismissed
{nitpick}
Bit unconventional to use `*string` as the return value, usually in errors funcs return just empty string with the error. 
{/nitpick}

2021-01-29 12:11 UTC, trawler commented
> {nitpick}
> Bit unconventional to use `*string` as the return value, usually in errors funcs return just empty string with the error.
> {/nitpick}

fixed

2021-01-29 12:15 UTC, ncopa requested changes
I think the term "address" is a bit misleading when it in really is an URL.

I think we should clean that up other places as well, but at least we should not add more confusion.

2021-01-29 12:15 UTC, ncopa commented on cmd/kubeconfig.go
> +			clusterAPIAddress, err := getAPIAddress()
```suggestion
			clusterAPIURL, err := getAPIURL()
```

2021-01-29 12:15 UTC, ncopa commented on cmd/kubeconfig.go
> +				JoinURL:    *clusterAPIAddress,
```suggestion
				JoinURL:    *clusterAPIURL,
```

2021-01-29 12:15 UTC, ncopa commented on cmd/kubeconfig.go
> +				clusterAPIAddress, err := getAPIAddress()
```suggestion
				clusterAPIURL, err := getAPIURL()
```

2021-01-29 12:15 UTC, ncopa commented on cmd/kubeconfig.go
> +				newContent := strings.Replace(string(content), "https://localhost:6443", clusterAPIAddress, -1)
```suggestion
				newContent := strings.Replace(string(content), "https://localhost:6443", clusterAPIURL, -1)
```

2021-01-29 12:15 UTC, ncopa commented on cmd/kubeconfig.go
> +func getAPIAddress() (string, error) {
```suggestion
func getAPIURL() (string, error) {
```

2021-01-29 12:15 UTC, ncopa commented on cmd/kubeconfig.go
> +	return address, nil
```suggestion
	return clusterConfig.Spec.API.APIAddress(), nil
```

Or does that not work?

2021-02-01 11:08 UTC, trawler commented
I added an APIAddressURL in this commit: https://github.com/k0sproject/k0s/tree/e72d12c92ab7c9ed34103398a3ec00c324720c59

Once merged, I'll rebased this PR.

2021-02-01 11:11 UTC, ncopa submitted a review, later dismissed

2021-02-03 10:20 UTC, merged