check if env var ETCD_UNSUPPORTED_ARCH has been set for ARM processors
k0sproject/k0s pull request #692
Opened 2021-02-09 15:20 UTC by jasmingacic

Fixes #424 
The PR will check if requested environment variable is set. If not it will print an error message in k0s logs.

2021-02-11 08:16 UTC, jnummelin requested changes

2021-02-11 08:16 UTC, jnummelin commented on pkg/component/controller/etcd.go
> +		if _, set := os.LookupEnv("ETCD_UNSUPPORTED_ARCH"); !set {
```suggestion
		if os.Getenv("ETCD_UNSUPPORTED_ARCH") != runtime.ARCH {
```
The current way makes the check pass in e.g. `arm64` archi bu setting up env `ETCD_UNSUPPORTED_ARCH=foo`. And that'll trip over etcd again.

2021-02-16 12:00 UTC, jnummelin approved these changes

2021-02-16 12:33 UTC, merged

2022-03-28 11:35 UTC, ypnos commented
Now when I start K0s I get the error as expected.
However when I set the environment variable, I find this in the logs:

> time="2022-03-28 13:24:49" level=info msg="{\"level\":\"warn\",\"ts\":1648466689.203589,\"caller\":\"flags/flag.go:93\",\"msg\":\"unrecognized environment variable\",\"environment-variable\":\"ETCD_UNSUPPORTED_ARCH=arm64\"}" component=etcd

In etcd documentation, ARM64 is now also listed as supported: https://etcd.io/docs/v3.5/op-guide/supported-platform/

So I wonder if this is still necessary or should be reverted?

2022-03-28 14:11 UTC, twz123 commented
See #1624