CSR Approver
k0sproject/k0s pull request #708
Opened 2021-02-15 12:41 UTC by jasmingacic

Fixes #83 

This PR also has a fix for konnectivity yaml which was malformed.

2021-02-16 11:27 UTC, jnummelin reviewed
We definitely need some unit tests for the CSR approver parts as it's pretty critical stuff to get right

2021-02-16 11:27 UTC, jnummelin commented on pkg/component/controller/csrapprover.go
> +	if (len(x509cr.DNSNames) < 1) || (len(x509cr.IPAddresses) < 1) {
```suggestion
	if (len(x509cr.DNSNames) < 1) && (len(x509cr.IPAddresses) < 1) {
```

2021-02-16 11:27 UTC, jnummelin commented on pkg/component/controller/csrapprover.go
> +func (a *CSRApprover) approveCSR() error {
Maybe add a note that this is adapted from rubber stamper

2021-02-16 11:27 UTC, jnummelin commented on pkg/component/controller/csrapprover.go
> +		Reason:  "Autoapproved by K0S CSRApprover",
```suggestion
		Reason:  "Autoapproved by k0s CSRApprover",
```

2021-02-16 17:01 UTC, jasmingacic commented on pkg/component/controller/csrapprover_test.go
> +	assert.Error(t, err)
Indeed

2021-02-17 11:48 UTC, trawler requested changes

2021-02-18 09:33 UTC, jasmingacic commented on pkg/component/controller/apiserver.go
> +		"kubelet-certificate-authority":    path.Join(a.K0sVars.CertRootDir, "ca.crt"),
The rest of the file uses only path.Join. I suppose then the entire file should be change

2021-02-18 10:25 UTC, jnummelin commented on pkg/component/controller/csrapprover.go
> +}
with the cert rotation enabled for both client & serving certs, kubelet will do CSRs for both separately. thus in the CSR approver we're only interested in the serving certs and safely ignore the possible client auth certs.

2021-02-18 10:32 UTC, jnummelin commented on pkg/component/controller/apiserver.go
> +		"kubelet-certificate-authority":    path.Join(a.K0sVars.CertRootDir, "ca.crt"),
Maybe keep this PR using `path.Join` as it's conformant with the rest of the usages in this file. Then a separate PR to refactor it to use `filepath.Join`

2021-02-18 12:14 UTC, jnummelin commented
Triggered network conformance at: https://github.com/k0sproject/k0s/actions/runs/578058009

2021-02-19 08:25 UTC, jnummelin approved these changes

2021-02-19 08:47 UTC, merged