convert relative file path to absolute
k0sproject/k0s pull request #750
Opened 2021-03-03 11:27 UTC by jasmingacic

When CLI parameters are converted to `--key=value` format,  file paths need to be absolute. 
This PR converts relative file path for parameters `--data-dir` `--config` and `--token-file` 
Closes #749

2021-03-08 10:27 UTC, soider submitted a review, later dismissed

2021-03-10 11:45 UTC, jnummelin requested changes

2021-03-10 11:45 UTC, jnummelin commented on cmd/install.go
> +func isDirectory(path string) bool {
We've got this already available in utils, re-use from there.

2021-03-10 11:45 UTC, jnummelin commented on cmd/install.go
> +func convertParamsToAbsolute() (err error) {
```suggestion
func convertFileParamsToAbsolute() (err error) {
```

2021-03-10 12:20 UTC, jnummelin approved these changes

2021-03-10 13:14 UTC, merged