k0s reset: support for docker
k0sproject/k0s pull request #955
Opened 2021-06-03 10:43 UTC by jewertow

**Issue**
Fixes #742

**What this PR Includes**
The purpose of this PR is to support docker and CRI-compatible container runtimes by `k0s reset` command.

2021-06-07 10:39 UTC, kke commented on cmd/reset/reset.go
> +		logger.Fatalf("Failed to configure clenup: %v", err)
```suggestion
		logger.Fatalf("Failed to configure cleanup: %v", err)
```

2021-06-07 10:41 UTC, kke commented on pkg/config/cli.go
> +	flagset.StringVar(&workerOpts.CriSocket, "cri-socket", "", "contrainer runtime socket to use, default to internal containerd. Format: [remote|docker]:[path-to-socket]")
```suggestion
	flagset.StringVar(&workerOpts.CriSocket, "cri-socket", "", "container runtime socket to use, default to internal containerd. Format: [remote|docker]:[path-to-socket]")
```

2021-06-08 21:25 UTC, jewertow commented on cmd/reset/reset.go
> +		logger.Fatalf("Failed to configure clenup: %v", err)
Fixed

2021-06-08 21:25 UTC, jewertow commented on pkg/config/cli.go
> +	flagset.StringVar(&workerOpts.CriSocket, "cri-socket", "", "contrainer runtime socket to use, default to internal containerd. Format: [remote|docker]:[path-to-socket]")
Fixed

2021-06-09 07:33 UTC, kke commented
overlaps with #959 - @jasmingacic should this come before or after? :)

2021-06-09 08:18 UTC, jasmingacic commented
@kke I would suggest that we integrate this later since the logic has changed significantly.

2021-06-09 08:22 UTC, jewertow commented
Ok, so can I come back to this feature when your pull request will be merged, right?

2021-06-09 09:01 UTC, jasmingacic commented
@jewertow yes you can but implementation will differ significantly

2021-06-14 07:59 UTC, jasmingacic commented
@jewertow go ahead and have this refactored so it fits into new design.

2021-06-16 22:40 UTC, jewertow commented
@jasmingacic I rebased commits and refactored code. Please review this change.

2021-06-16 23:44 UTC, jasmingacic requested changes
Passing "cri-socket" to `k0s reset` doesn't feel right.  Ideally the users should just run `k0s reset` to remove all k0s leftovers. 

I know that we discover containerd by looking for the containerd binary in dataDir/bin/containerd and also by checking if this statement is true `c.Config.containerd == nil` can we based on that figure out `--docker-endpoint` that's passed to the kubelet process. 

We know based on `k0s status` PID of k0s process and  get kubelet by PPID
```
# pstree $K0SPID
k0s─┬─etcd───96*[{etcd}]
   ...
    ├─kubelet───57*[{kubelet}]
    └─64*[{k0s}]
``` 

We already have something similar here -> `https://github.com/k0sproject/k0s/blob/main/pkg/install/process.go`

2021-06-17 09:06 UTC, jewertow commented
@jasmingacic `pstree $K0SPID` will not return `k0s` and `kubelet` processes after k0s has stoppped, so `reset` can't relay on it.

2021-06-17 09:08 UTC, jewertow commented
Maybe command `install` could store CRI socket path somewhere to make it possible for `reset` to use this path later?

2021-06-17 09:16 UTC, jasmingacic approved these changes
Since we don't have any better way to do it, this solution is good.

2021-06-17 09:57 UTC, kke commented
> Maybe command `install` could store CRI socket path somewhere to make it possible for `reset` to use this path later?

Yeah this should be in the status socket api that has been discussed a couple of times lately.

2021-06-17 10:27 UTC, ncopa approved these changes
LGTM

2021-06-17 10:28 UTC, merged